### PR TITLE
Use PolyBuilder to fill if the shape has holes

### PR DESCRIPTION
**Pull request by dev7355608**
Holes in shapes other than Polygon are not working.

I compared it to standard Graphics (https://github.com/pixijs/pixijs/blob/7ee2be5cf88bb990166db10cfb017e37aa2cbbb1/packages/graphics/src/GraphicsGeometry.ts#L763-L777) and made the change accordingly. This seems to do the trick.

### CODE REVIEW

**Comment by dev7355608** [comment]
Circular holes were not working correctly yet. Fixed it: Center point of the circle is no longer added to `points` in `path`, but transformed and added to `verts` in `fill`. This is how standard Graphics handles the center point as well.

**Comment by ghost91-** [comment]
Hey there, any news on this? I Also just ran into this bug. I Will have to keep using the standard Graphics for now for this reason...

**Comment by ivanpopelyshev** [comment]
I exited pixijs team to not get involved for some time and get rest, i cant really merge this. 

@dev7355608 ask @bigtimebuddy to give you rights on this repo

**Comment by bigtimebuddy** [comment]
@dev7355608 made you a maintainer if you want to contribute directly to this plugin, you have our blessing. Happy to help in whatever way you need.

**Pull request merged**
