### PR TITLE
updated to work on pixi v7

### PR DESCRIPTION
**Pull request by miltoncandelero**
updated to work on v7

- added compatibility with pixi v7
  - small hack to get the antialias of the gl context
  - updated deps to pixi v7
- updated typescript version to last working version for building libs
- broken compatibility with pixi v6
  - We will need some different version number or something
  - When can this be official graphics?

texted on pixi.js bundle v7

### CODE REVIEW

**Comment by miltoncandelero** [comment]
fixes #29 but we need an strategy for releasing this

**Comment by dev7355608** [comment]
Removed `nextRoundedRectBehavior` and corrected the antialias check. The original check is actually problematic, because it checks whether the renderer's canvas is multisampled instead whether the current render target is; maybe this should be correct in the v6 version of the library too.

Not sure what the versioning strategy should be. I guess 0.1.0?

**Comment by ivanpopelyshev** [comment]
make it 0.1.0 :)

**Comment by ivanpopelyshev** [comment]
I mean , make it 1.0.0 , the lib is used a lot already.

**Comment by bigtimebuddy** [comment]
Thanks @miltoncandelero, but I'd like to replace this with #32. I cherry-picked @dev7355608's changes above, but did a little more to clean-up this project and make it a little more on-par with other plugins.

**Pull request closed without merging**
